### ISSUE TITLE
 what can it be?

### ISSUE THREAD

**Issue by claudiowwe** [LoL-Human/bot-wa#4]
╭─── [ LOG ]
/root/bot-wa/libs/utils/utils/utility.util.js:63
let category = command?.category
___________________________^

SyntaxError: Unexpected token '.'
at wrapSafe (internal/modules/cjs/loader.js:915:16)
at Module._compile (internal/modules/cjs/loader.js:963:27)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
at Module.load (internal/modules/cjs/loader.js:863:32)
at Function.Module._load (internal/modules/cjs/loader.js:708:14)
at Module.require (internal/modules/cjs/loader.js:887:19)
at require (internal/modules/cjs/helpers.js:74:18)
at Object. (/root/bot-wa/libs/connect.lib.js:2:21)
at Module._compile (internal/modules/cjs/loader.js:999:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
npm ERR! code 1
npm ERR! path /root/bot-wa
npm ERR! command failed
npm ERR! command sh -c node .

npm ERR! A complete log of this run can be found in:
npm ERR! /root/.npm/_logs/2022-07-21T06_13_28_899Z-debug.log

I have tried it on a vps with debian and ubuntu, and I only have syntax errors, what can it be?

**Comment by LoL-Human** [comment]
please update your node js
